In [1]:
import os
import pandas as pd
from pathlib import Path
import json

# Leitura do Excel

In [2]:
taco = pd.read_excel(Path(os.getcwd(), "docs", "TACO_Tabel.xlsx"), sheet_name = "Taco", index_col = 0)
taco

,Nome,Preparo,Carboidrato (g),Proteína (g),Lipídeos (g),Energia (Kcal),Umidade,Energia (KJ),Colesterol (mg),Fibra Alimentar (g),...,Cobre (mg),Zinco (mg),Retinol (μg),RE (μg),RAE (μg),Tiamina (mg),Riboflavina (mg),Piridoxina (mg),Niacina (mg),Vitamina C (mg)
ID,,,,,,,,,,,,,,,,,,,,,
1,Arroz,"integral, cozido","25,8","2,6","1,0",124,"70,1",517,0,"2,7",...,"0,3",1,75,"0,02","0,7",0,"0,08",0,"0,08",0
2,Arroz,"integral, cru","77,5","7,3","1,9",360,"12,2",1505,0,"4,8",...,"0,9",2,173,"0,07","1,4",0,"0,26",0,"0,18","4,18"
3,Arroz,"tipo 1, cozido","28,1","2,5","0,2",128,"69,1",537,0,"1,6",...,"0,1",1,15,"0,02","0,5",0,0,0,0,0
4,Arroz,"tipo 1, cru","78,8","7,2","0,3",358,"13,2",1497,0,"1,6",...,"0,7",1,62,"0,11","1,2",0,"0,16",0,"0,07","1,12"
5,Arroz,"tipo 2, cozido","28,2","2,6","0,4",130,"68,7",544,0,"1,1",...,"0,1",2,20,"0,04","0,5",0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,Gergelim,semente,"21,6","21,2","50,4",584,"3,9",2442,0,"11,9",...,3,546,"1,51","5,2",0,"0,94",0,"0,13","5,92",0
594,Linhaça,semente,"43,3","14,1","32,3",495,"6,7",2072,0,"33,5",...,9,869,"1,09","4,4",0,"0,12",0,"0,13",0,0
595,Pinhão,cozido,"43,9","3,0","0,7",174,"50,5",730,0,"15,6",...,1,727,"0,18","0,8",0,0,0,0,0,"27,7"
596,Pupunha,cozida,"29,6","2,5","12,8",219,"54,5",914,0,"4,3",...,"0,28","0,3",0,875,438,0,"0,09","0,03",0,"2,2"
597,Noz,crua,"18,4","14,0","59,4",620,"6,2",2594,0,"7,2",...,5,533,"0,75","2,1",0,"0,38",0,"0,13","1,08",0

In [3]:
taco.info()

<class 'pandas.core.frame.DataFrame'>
Index: 597 entries, 1 to 597
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Nome                 597 non-null    object
 1   Preparo              595 non-null    object
 2   Carboidrato (g)      597 non-null    object
 3   Proteína (g)         597 non-null    object
 4   Lipídeos (g)         597 non-null    object
 5   Energia (Kcal)       597 non-null    object
 6   Umidade              597 non-null    object
 7   Energia (KJ)         597 non-null    object
 8   Colesterol (mg)      597 non-null    object
 9   Fibra Alimentar (g)  597 non-null    object
 10  Cinzas (g)           597 non-null    object
 11  Cálcio (mg)          597 non-null    object
 12  Magnésio (mg)        597 non-null    object
 13  Manganês (mg)        597 non-null    object
 14  Fósforo (mg)         597 non-null    object
 15  Ferro (mg)           597 non-null    object
 16  Sódio (mg)           597 non-null    int64
 17  Potássio (mg)        597 non-null    object
 18  Cobre (mg)           597 non-null    object
 19  Zinco (mg)           597 non-null    object
 20  Retinol (μg)         597 non-null    object
 21  RE (μg)              597 non-null    object
 22  RAE (μg)             597 non-null    object
 23  Tiamina (mg)         597 non-null    object
 24  Riboflavina (mg)     597 non-null    object
 25  Piridoxina (mg)      597 non-null    object
 26  Niacina (mg)         597 non-null    object
 27  Vitamina C (mg)      597 non-null    object
dtypes: int64(1), object(27)
memory usage: 135.3+ KB

In [4]:
taco = taco.replace("Tr", 0.0)
taco = taco.replace("NA", 0.0)
taco

,Nome,Preparo,Carboidrato (g),Proteína (g),Lipídeos (g),Energia (Kcal),Umidade,Energia (KJ),Colesterol (mg),Fibra Alimentar (g),...,Cobre (mg),Zinco (mg),Retinol (μg),RE (μg),RAE (μg),Tiamina (mg),Riboflavina (mg),Piridoxina (mg),Niacina (mg),Vitamina C (mg)
ID,,,,,,,,,,,,,,,,,,,,,
1,Arroz,"integral, cozido","25,8","2,6","1,0",124,"70,1",517,0,"2,7",...,"0,3",1,75,"0,02","0,7",0,"0,08",0,"0,08",0
2,Arroz,"integral, cru","77,5","7,3","1,9",360,"12,2",1505,0,"4,8",...,"0,9",2,173,"0,07","1,4",0,"0,26",0,"0,18","4,18"
3,Arroz,"tipo 1, cozido","28,1","2,5","0,2",128,"69,1",537,0,"1,6",...,"0,1",1,15,"0,02","0,5",0,0,0,0,0
4,Arroz,"tipo 1, cru","78,8","7,2","0,3",358,"13,2",1497,0,"1,6",...,"0,7",1,62,"0,11","1,2",0,"0,16",0,"0,07","1,12"
5,Arroz,"tipo 2, cozido","28,2","2,6","0,4",130,"68,7",544,0,"1,1",...,"0,1",2,20,"0,04","0,5",0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,Gergelim,semente,"21,6","21,2","50,4",584,"3,9",2442,0,"11,9",...,3,546,"1,51","5,2",0,"0,94",0,"0,13","5,92",0
594,Linhaça,semente,"43,3","14,1","32,3",495,"6,7",2072,0,"33,5",...,9,869,"1,09","4,4",0,"0,12",0,"0,13",0,0
595,Pinhão,cozido,"43,9","3,0","0,7",174,"50,5",730,0,"15,6",...,1,727,"0,18","0,8",0,0,0,0,0,"27,7"
596,Pupunha,cozida,"29,6","2,5","12,8",219,"54,5",914,0,"4,3",...,"0,28","0,3",0,875,438,0,"0,09","0,03",0,"2,2"
597,Noz,crua,"18,4","14,0","59,4",620,"6,2",2594,0,"7,2",...,5,533,"0,75","2,1",0,"0,38",0,"0,13","1,08",0

# Filtrando com base nos alimentos pré selecionados

In [5]:
# Lendo o arquivo JSON
with open(Path(os.getcwd(), "infos", "alimentos_selecionados.json"), 'r') as f:
    data = json.load(f)

# Acessando os dados
alimentos_gramas = data['alimentos_gramas']
alimentos_inteiros = data['alimentos_unidade']
gramas_unidade = data["gramas_por_unidade"]
alimentos_gramas, alimentos_inteiros, gramas_unidade

([3, 7, 26, 410, 456, 567, 524, 260, 377, 131, 116],
 [179, 222, 488, 213],
 [150, 100, 50, 150])

In [6]:
df = taco.loc[alimentos_gramas, :]
df["Tipo"] = "gramas"
df

,Nome,Preparo,Carboidrato (g),Proteína (g),Lipídeos (g),Energia (Kcal),Umidade,Energia (KJ),Colesterol (mg),Fibra Alimentar (g),...,Zinco (mg),Retinol (μg),RE (μg),RAE (μg),Tiamina (mg),Riboflavina (mg),Piridoxina (mg),Niacina (mg),Vitamina C (mg),Tipo
ID,,,,,,,,,,,,,,,,,,,,,
3,Arroz,"tipo 1, cozido","28,1","2,5","0,2",128,"69,1",537,0,"1,6",...,1,15,"0,02","0,5",0,0,0,0,0,gramas
7,Aveia,"flocos, crua","66,6","13,9","8,5",394,"9,1",1648,0,"9,1",...,336,"0,44","2,6",0,"0,55","0,03",0,"4,47","1,4",gramas
26,Cereal matinal,"milho, açúcar","88,8","4,7","0,7",377,"4,3",1576,0,"2,1",...,"8,5",0,31,15,"0,73","1,11","0,79","10,13","14,6",gramas
410,Frango,"peito, sem pele, grelhado","0,0","32,0","2,5",159,"63,8",666,89,0,...,"0,02","0,8",0,0,0,"0,11",0,0,"24,83",gramas
456,Leite,"de vaca, desnatado, pó","53,0","34,7","0,9",362,"3,1",1513,25,0,...,432,1556,"0,16","3,8",299,"0,32","1,20",0,"0,81",gramas
567,Feijão,"preto, cozido","14,0","4,5","0,5",77,"80,2",322,0,"8,4",...,256,"0,20","0,7",0,"0,06",0,"0,03",0,0,gramas
524,Maionese,tradicional com ovos,"7,9","0,6","30,5",302,"58,4",1264,42,0,...,16,0,"0,1",8,0,"0,05",0,0,0,gramas
260,Azeite,"de oliva, extra virgem",0,0,"100,0",884,0,3699,0,0,...,0,0,0,0,0,0,0,0,0,gramas
377,Carne,"bovina, patinho, sem gordura, grelhado","0,0","35,9","7,3",219,"55,2",917,126,0,...,"0,12","8,1",0,0,0,"0,04","0,03",0,"3,01",gramas
131,Mandioca,"farofa, temperada","80,3","2,1","9,1",406,"6,4",1697,0,"7,8",...,201,0,"0,2",0,"0,10",0,"0,15",0,0,gramas
116,Couve,"manteiga, refogada","8,7","1,7","6,6",90,"81,5",378,0,"5,7",...,"0,2",0,384b,192b,0,"0,05","0,07",0,"76,9",gramas

In [7]:
df_temp = taco.loc[alimentos_inteiros, :]
df_temp["Tipo"] = "inteiros"
df_temp

,Nome,Preparo,Carboidrato (g),Proteína (g),Lipídeos (g),Energia (Kcal),Umidade,Energia (KJ),Colesterol (mg),Fibra Alimentar (g),...,Zinco (mg),Retinol (μg),RE (μg),RAE (μg),Tiamina (mg),Riboflavina (mg),Piridoxina (mg),Niacina (mg),Vitamina C (mg),Tipo
ID,,,,,,,,,,,,,,,,,,,,,
179,Banana,"nanica, crua","23,8","1,4","0,1",92,"73,8",383,0,"1,9",...,"0,2",0,14,7,0,"0,02","0,14",0,"5,9",inteiros
222,Maçã,"Fuji, com casca, crua","15,2","0,3",0,56,"84,3",232,0,"1,3",...,0,0,4,2,0,0,"0,03",0,"2,4",inteiros
488,Ovo,"de galinha, inteiro, cozido/10minutos","0,6","13,3","9,5",146,"75,8",610,397,0,...,146,139,"0,04","1,2",32,"0,08","0,30",0,0,inteiros
213,Laranja,"lima, suco","9,2","0,7","0,1",39,"89,7",165,0,"0,4",...,129,"0,02","0,0",0,"0,10","0,03","0,04",0,"41,3",inteiros

In [8]:
base_df = pd.concat([df, df_temp])
base_df

,Nome,Preparo,Carboidrato (g),Proteína (g),Lipídeos (g),Energia (Kcal),Umidade,Energia (KJ),Colesterol (mg),Fibra Alimentar (g),...,Zinco (mg),Retinol (μg),RE (μg),RAE (μg),Tiamina (mg),Riboflavina (mg),Piridoxina (mg),Niacina (mg),Vitamina C (mg),Tipo
ID,,,,,,,,,,,,,,,,,,,,,
3,Arroz,"tipo 1, cozido","28,1","2,5","0,2",128,"69,1",537,0,"1,6",...,1,15,"0,02","0,5",0,0,0,0,0,gramas
7,Aveia,"flocos, crua","66,6","13,9","8,5",394,"9,1",1648,0,"9,1",...,336,"0,44","2,6",0,"0,55","0,03",0,"4,47","1,4",gramas
26,Cereal matinal,"milho, açúcar","88,8","4,7","0,7",377,"4,3",1576,0,"2,1",...,"8,5",0,31,15,"0,73","1,11","0,79","10,13","14,6",gramas
410,Frango,"peito, sem pele, grelhado","0,0","32,0","2,5",159,"63,8",666,89,0,...,"0,02","0,8",0,0,0,"0,11",0,0,"24,83",gramas
456,Leite,"de vaca, desnatado, pó","53,0","34,7","0,9",362,"3,1",1513,25,0,...,432,1556,"0,16","3,8",299,"0,32","1,20",0,"0,81",gramas
567,Feijão,"preto, cozido","14,0","4,5","0,5",77,"80,2",322,0,"8,4",...,256,"0,20","0,7",0,"0,06",0,"0,03",0,0,gramas
524,Maionese,tradicional com ovos,"7,9","0,6","30,5",302,"58,4",1264,42,0,...,16,0,"0,1",8,0,"0,05",0,0,0,gramas
260,Azeite,"de oliva, extra virgem",0,0,"100,0",884,0,3699,0,0,...,0,0,0,0,0,0,0,0,0,gramas
377,Carne,"bovina, patinho, sem gordura, grelhado","0,0","35,9","7,3",219,"55,2",917,126,0,...,"0,12","8,1",0,0,0,"0,04","0,03",0,"3,01",gramas
131,Mandioca,"farofa, temperada","80,3","2,1","9,1",406,"6,4",1697,0,"7,8",...,201,0,"0,2",0,"0,10",0,"0,15",0,0,gramas
116,Couve,"manteiga, refogada","8,7","1,7","6,6",90,"81,5",378,0,"5,7",...,"0,2",0,384b,192b,0,"0,05","0,07",0,"76,9",gramas
179,Banana,"nanica, crua","23,8","1,4","0,1",92,"73,8",383,0,"1,9",...,"0,2",0,14,7,0,"0,02","0,14",0,"5,9",inteiros
222,Maçã,"Fuji, com casca, crua","15,2","0,3",0,56,"84,3",232,0,"1,3",...,0,0,4,2,0,0,"0,03",0,"2,4",inteiros
488,Ovo,"de galinha, inteiro, cozido/10minutos","0,6","13,3","9,5",146,"75,8",610,397,0,...,146,139,"0,04","1,2",32,"0,08","0,30",0,0,inteiros
213,Laranja,"lima, suco","9,2","0,7","0,1",39,"89,7",165,0,"0,4",...,129,"0,02","0,0",0,"0,10","0,03","0,04",0,"41,3",inteiros

In [9]:
base_df = base_df.replace("b", "", regex = True)
base_df

,Nome,Preparo,Carboidrato (g),Proteína (g),Lipídeos (g),Energia (Kcal),Umidade,Energia (KJ),Colesterol (mg),Fibra Alimentar (g),...,Zinco (mg),Retinol (μg),RE (μg),RAE (μg),Tiamina (mg),Riboflavina (mg),Piridoxina (mg),Niacina (mg),Vitamina C (mg),Tipo
ID,,,,,,,,,,,,,,,,,,,,,
3,Arroz,"tipo 1, cozido","28,1","2,5","0,2",128,"69,1",537,0,"1,6",...,1,15,"0,02","0,5",0,0,0,0,0,gramas
7,Aveia,"flocos, crua","66,6","13,9","8,5",394,"9,1",1648,0,"9,1",...,336,"0,44","2,6",0,"0,55","0,03",0,"4,47","1,4",gramas
26,Cereal matinal,"milho, açúcar","88,8","4,7","0,7",377,"4,3",1576,0,"2,1",...,"8,5",0,31,15,"0,73","1,11","0,79","10,13","14,6",gramas
410,Frango,"peito, sem pele, grelhado","0,0","32,0","2,5",159,"63,8",666,89,0,...,"0,02","0,8",0,0,0,"0,11",0,0,"24,83",gramas
456,Leite,"de vaca, desnatado, pó","53,0","34,7","0,9",362,"3,1",1513,25,0,...,432,1556,"0,16","3,8",299,"0,32","1,20",0,"0,81",gramas
567,Feijão,"preto, cozido","14,0","4,5","0,5",77,"80,2",322,0,"8,4",...,256,"0,20","0,7",0,"0,06",0,"0,03",0,0,gramas
524,Maionese,tradicional com ovos,"7,9","0,6","30,5",302,"58,4",1264,42,0,...,16,0,"0,1",8,0,"0,05",0,0,0,gramas
260,Azeite,"de oliva, extra virgem",0,0,"100,0",884,0,3699,0,0,...,0,0,0,0,0,0,0,0,0,gramas
377,Carne,"ovina, patinho, sem gordura, grelhado","0,0","35,9","7,3",219,"55,2",917,126,0,...,"0,12","8,1",0,0,0,"0,04","0,03",0,"3,01",gramas
131,Mandioca,"farofa, temperada","80,3","2,1","9,1",406,"6,4",1697,0,"7,8",...,201,0,"0,2",0,"0,10",0,"0,15",0,0,gramas
116,Couve,"manteiga, refogada","8,7","1,7","6,6",90,"81,5",378,0,"5,7",...,"0,2",0,384,192,0,"0,05","0,07",0,"76,9",gramas
179,Banana,"nanica, crua","23,8","1,4","0,1",92,"73,8",383,0,"1,9",...,"0,2",0,14,7,0,"0,02","0,14",0,"5,9",inteiros
222,Maçã,"Fuji, com casca, crua","15,2","0,3",0,56,"84,3",232,0,"1,3",...,0,0,4,2,0,0,"0,03",0,"2,4",inteiros
488,Ovo,"de galinha, inteiro, cozido/10minutos","0,6","13,3","9,5",146,"75,8",610,397,0,...,146,139,"0,04","1,2",32,"0,08","0,30",0,0,inteiros
213,Laranja,"lima, suco","9,2","0,7","0,1",39,"89,7",165,0,"0,4",...,129,"0,02","0,0",0,"0,10","0,03","0,04",0,"41,3",inteiros

In [10]:
base_df = base_df.drop(["Preparo", "Energia (Kcal)", "Umidade", "Energia (KJ)", "Cinzas (g)", "RE (μg)", "RAE (μg)"], axis = 1)
base_df

,Nome,Carboidrato (g),Proteína (g),Lipídeos (g),Colesterol (mg),Fibra Alimentar (g),Cálcio (mg),Magnésio (mg),Manganês (mg),Fósforo (mg),...,Potássio (mg),Cobre (mg),Zinco (mg),Retinol (μg),Tiamina (mg),Riboflavina (mg),Piridoxina (mg),Niacina (mg),Vitamina C (mg),Tipo
ID,,,,,,,,,,,,,,,,,,,,,
3,Arroz,"28,1","2,5","0,2",0,"1,6",4,2,"0,30",0,...,18,"0,1",1,15,0,0,0,0,0,gramas
7,Aveia,"66,6","13,9","8,5",0,"9,1",48,119,"1,89",153,...,"4,4",5,336,"0,44","0,55","0,03",0,"4,47","1,4",gramas
26,Cereal matinal,"88,8","4,7","0,7",0,"2,1",56,8,"0,13",43,...,52,"0,04","8,5",0,"0,73","1,11","0,79","10,13","14,6",gramas
410,Frango,"0,0","32,0","2,5",89,0,5,18,0,295,...,50,387,"0,02","0,8",0,"0,11",0,0,"24,83",gramas
456,Leite,"53,0","34,7","0,9",25,0,1363,109,0,0,...,1673,"0,9",432,1556,299,"0,32","1,20",0,"0,81",gramas
567,Feijão,"14,0","4,5","0,5",0,"8,4",29,40,"0,37",88,...,"1,5",2,256,"0,20","0,06",0,"0,03",0,0,gramas
524,Maionese,"7,9","0,6","30,5",42,0,3,1,0,14,...,"0,1",787,16,0,0,"0,05",0,0,0,gramas
260,Azeite,0,0,"100,0",0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,gramas
377,Carne,"0,0","35,9","7,3",126,0,5,27,"0,02",289,...,60,421,"0,12","8,1",0,"0,04","0,03",0,"3,01",gramas
131,Mandioca,"80,3","2,1","9,1",0,"7,8",66,34,"0,29",45,...,"1,4",575,201,0,"0,10",0,"0,15",0,0,gramas
116,Couve,"8,7","1,7","6,6",0,"5,7",177,26,"0,12",33,...,315,"0,02","0,2",0,0,"0,05","0,07",0,"76,9",gramas
179,Banana,"23,8","1,4","0,1",0,"1,9",3,28,"0,14",27,...,376,"0,10","0,2",0,0,"0,02","0,14",0,"5,9",inteiros
222,Maçã,"15,2","0,3",0,0,"1,3",2,2,"0,03",9,...,75,"0,06",0,0,0,0,"0,03",0,"2,4",inteiros
488,Ovo,"0,6","13,3","9,5",397,0,49,11,"0,02",0,...,184,"1,5",146,139,32,"0,08","0,30",0,0,inteiros
213,Laranja,"9,2","0,7","0,1",0,"0,4",8,11,"0,02",16,...,0,0,129,"0,02","0,10","0,03","0,04",0,"41,3",inteiros

In [11]:
df = base_df.drop(["Nome", "Tipo"], axis = 1).replace(',', '.', regex=True).astype(float).copy()
df = df/100 #dividindo por 100 gramas (base das contas)
for k, id_int in enumerate(alimentos_inteiros):
    df.loc[id_int] = df.loc[id_int]*gramas_unidade[k]
df["Nome"] = base_df["Nome"]
df["Tipo"] = base_df["Tipo"]
df

,Carboidrato (g),Proteína (g),Lipídeos (g),Colesterol (mg),Fibra Alimentar (g),Cálcio (mg),Magnésio (mg),Manganês (mg),Fósforo (mg),Ferro (mg),...,Cobre (mg),Zinco (mg),Retinol (μg),Tiamina (mg),Riboflavina (mg),Piridoxina (mg),Niacina (mg),Vitamina C (mg),Nome,Tipo
ID,,,,,,,,,,,,,,,,,,,,,
3,0.281,0.025,0.002,0.00,0.016,0.04,0.02,0.0030,0.00,0.000,...,0.0010,0.0100,0.1500,0.0000,0.0000,0.0000,0.0000,0.0000,Arroz,gramas
7,0.666,0.139,0.085,0.00,0.091,0.48,1.19,0.0189,1.53,0.000,...,0.0500,3.3600,0.0044,0.0055,0.0003,0.0000,0.0447,0.0140,Aveia,gramas
26,0.888,0.047,0.007,0.00,0.021,0.56,0.08,0.0013,0.43,0.039,...,0.0004,0.0850,0.0000,0.0073,0.0111,0.0079,0.1013,0.1460,Cereal matinal,gramas
410,0.000,0.320,0.025,0.89,0.000,0.05,0.18,0.0000,2.95,0.003,...,3.8700,0.0002,0.0080,0.0000,0.0011,0.0000,0.0000,0.2483,Frango,gramas
456,0.530,0.347,0.009,0.25,0.000,13.63,1.09,0.0000,0.00,0.000,...,0.0090,4.3200,15.5600,2.9900,0.0032,0.0120,0.0000,0.0081,Leite,gramas
567,0.140,0.045,0.005,0.00,0.084,0.29,0.40,0.0037,0.88,0.000,...,0.0200,2.5600,0.0020,0.0006,0.0000,0.0003,0.0000,0.0000,Feijão,gramas
524,0.079,0.006,0.305,0.42,0.000,0.03,0.01,0.0000,0.14,0.000,...,7.8700,0.1600,0.0000,0.0000,0.0005,0.0000,0.0000,0.0000,Maionese,gramas
260,0.000,0.000,1.000,0.00,0.000,0.00,0.00,0.0000,0.00,0.000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,Azeite,gramas
377,0.000,0.359,0.073,1.26,0.000,0.05,0.27,0.0002,2.89,0.030,...,4.2100,0.0012,0.0810,0.0000,0.0004,0.0003,0.0000,0.0301,Carne,gramas
131,0.803,0.021,0.091,0.00,0.078,0.66,0.34,0.0029,0.45,0.000,...,5.7500,2.0100,0.0000,0.0010,0.0000,0.0015,0.0000,0.0000,Mandioca,gramas
116,0.087,0.017,0.066,0.00,0.057,1.77,0.26,0.0012,0.33,0.005,...,0.0002,0.0020,0.0000,0.0000,0.0005,0.0007,0.0000,0.7690,Couve,gramas
179,35.700,2.100,0.150,0.00,2.850,4.50,42.00,0.2100,40.50,0.450,...,0.1500,0.3000,0.0000,0.0000,0.0300,0.2100,0.0000,8.8500,Banana,inteiros
222,15.200,0.300,0.000,0.00,1.300,2.00,2.00,0.0300,9.00,0.100,...,0.0600,0.0000,0.0000,0.0000,0.0000,0.0300,0.0000,2.4000,Maçã,inteiros
488,0.300,6.650,4.750,198.50,0.000,24.50,5.50,0.0100,0.00,0.000,...,0.7500,73.0000,69.5000,16.0000,0.0400,0.1500,0.0000,0.0000,Ovo,inteiros
213,13.800,1.050,0.150,0.00,0.600,12.00,16.50,0.0300,24.00,0.000,...,0.0000,193.5000,0.0300,0.1500,0.0450,0.0600,0.0000,61.9500,Laranja,inteiros

In [12]:
df.to_csv(Path(os.getcwd(), "infos", "base_csv.csv"), index = False)